# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [101]:
import numpy as np

2. Create a null vector of size 10 

In [102]:
np.array(10)

array(10)

3. Create a vector with values ranging from 10 to 49

In [103]:
vector = np.arange(start=10, stop=49)

4. Find the shape of previous array in question 3

In [104]:
vector.shape

(39,)

5. Print the type of the previous array in question 3

In [105]:
print(vector.dtype)

int64


6. Print the numpy version and the configuration


In [106]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
blas_info:
    libraries = ['cblas', 'blas', 'blas']
    library_dirs = ['/usr/lib64']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'blas']
    library_dirs = ['/usr/lib64']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
l

7. Print the dimension of the array in question 3


In [107]:
vector.ndim

1

8. Create a boolean array with all the True values

In [108]:
np.ones([1, 10], dtype=bool)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

9. Create a two dimensional array




In [109]:
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

10. Create a three dimensional array



In [110]:
np.zeros((2, 3,3))


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [111]:
np.flip(vector)

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [112]:
x = np.zeros(10)
print(x)
print("Update fifth value to 1")
x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [113]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [114]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = arr.astype(np.float)
print(arr.dtype)

int64
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [115]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
              
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

res = arr1 * arr2
print(res)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [116]:
arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])

res = arr1 == arr2

print(res)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [117]:
array = np.arange(start=0, stop=10)

array[array % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [118]:
np.where(array % 2 == 1, -1, array)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [119]:
arr = np.arange(10)

arr[4:8] = 12
print(arr)

[ 0  1  2  3 12 12 12 12  8  9]


20. Create a 2d array with 1 on the border and 0 inside

In [120]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [121]:
arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [122]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d[0][0][:] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [123]:
x = np.arange(10).reshape((5,2))
print("Before Slicing")
print(x)
print("After Slicing")
print(x[0, 0:])

Before Slicing
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
After Slicing
[0 1]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [124]:
x = np.arange(10).reshape((5,2))
print("Before Slicing")
print(x)
print("After Slicing")
print(x[0, 1:2])

Before Slicing
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
After Slicing
[1]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [125]:
x = np.arange(10).reshape((5,2))
print("Before Slicing")
print(x)
print("After Slicing")
print(x[0:3, :])

Before Slicing
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
After Slicing
[[0 1]
 [2 3]
 [4 5]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [126]:
x = np.random.rand(10, 10)
print("10 x 10 array: {}".format(x))
maximum_value = np.max(x)
minimum_value = np.min(x)
print("Maximum value: {}".format(maximum_value))
print("Minimum value: {}".format(minimum_value))

10 x 10 array: [[0.85454781 0.99017397 0.84292194 0.35665745 0.96835868 0.24623876
  0.97388649 0.43512462 0.57799515 0.85310993]
 [0.79867727 0.62877289 0.9040127  0.43432224 0.44795109 0.2452329
  0.79954034 0.18825044 0.12051864 0.91233111]
 [0.01420093 0.69618012 0.05289934 0.33000815 0.36547017 0.41376157
  0.23506982 0.92504318 0.5764928  0.90698295]
 [0.76052806 0.84826958 0.0467483  0.48977931 0.61234289 0.19865141
  0.34386664 0.76744868 0.26847745 0.03732566]
 [0.1588226  0.23105094 0.66267097 0.62793963 0.45752169 0.41390113
  0.75517731 0.20776396 0.20768048 0.75781495]
 [0.53343507 0.70367989 0.66140644 0.77530657 0.79641893 0.80416917
  0.31785549 0.00387891 0.62359317 0.1403846 ]
 [0.80815888 0.3667277  0.0121138  0.8411007  0.71827245 0.24401556
  0.70067904 0.04716859 0.09040386 0.26824028]
 [0.36856823 0.65075005 0.20397461 0.83840796 0.99196371 0.83111307
  0.53270323 0.76082112 0.97175795 0.17237937]
 [0.32502173 0.80872211 0.69064484 0.54949881 0.58663965 0.3376893

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [127]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [128]:
np.where(np.in1d(a, b))

(array([1, 3, 5, 7]),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [129]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
print("Names: {}".format(names))
data = np.random.randn(7, 4)
print("Data: {}".format(data))

names_sorted = np.where(names != "Will")[0]

for index in names_sorted:
    print("Name: {}, Data: {}".format(names[index], data[index]))

Names: ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
Data: [[-0.20585322  1.87633455  1.50643572 -0.1543225 ]
 [ 0.76457105 -1.0119602   0.72537257  0.03817861]
 [ 0.45068105  1.41793875  0.86816912 -0.83346213]
 [-0.37716992  0.16981577 -1.31847218  0.28403659]
 [ 0.68968285 -1.23703148 -0.81421555 -1.75555206]
 [ 1.23734179  1.06210175 -0.39411415 -1.1141629 ]
 [ 0.36678477  0.7052349  -0.48836259 -0.32250831]]
Name: Bob, Data: [-0.20585322  1.87633455  1.50643572 -0.1543225 ]
Name: Joe, Data: [ 0.76457105 -1.0119602   0.72537257  0.03817861]
Name: Bob, Data: [-0.37716992  0.16981577 -1.31847218  0.28403659]
Name: Joe, Data: [ 1.23734179  1.06210175 -0.39411415 -1.1141629 ]
Name: Joe, Data: [ 0.36678477  0.7052349  -0.48836259 -0.32250831]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [130]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
print("Names: {}".format(names))
data = np.random.randn(7, 4)
print("Data: {}".format(data))

names_sorted = np.where((names != "Will") & (names != "Joe"))[0]

for index in names_sorted:
    print("Name: {}, Data: {}".format(names[index], data[index]))

Names: ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
Data: [[ 0.2185636   0.9733696  -0.66947194 -0.84300699]
 [-0.10303424 -0.24236673 -0.14084903 -0.22169163]
 [ 0.7112467  -1.57097561  0.26080172 -1.86625046]
 [-0.60858698 -2.30712339 -0.45423976  0.03108872]
 [ 0.92067463  0.35863189 -2.15862066  0.32192172]
 [-0.72318823  0.37512736  0.87699789  0.15033126]
 [ 1.76822302 -0.61852693 -0.32382459  1.11583945]]
Name: Bob, Data: [ 0.2185636   0.9733696  -0.66947194 -0.84300699]
Name: Bob, Data: [-0.60858698 -2.30712339 -0.45423976  0.03108872]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [131]:
array = np.arange(start=1, stop=16)
array = array.reshape([5, 3])
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [132]:
array = np.arange(start=1, stop=17)
array = array.reshape((2,2,4))

array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [133]:
np.swapaxes(array, 0, 1)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [134]:
x = np.arange(10)
print(x)

x = np.sqrt(x)
print(x)
x = np.where(x < 0.5, 0, x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [135]:
a = np.random.rand(12)
b = np.random.rand(12)
print(a)
print(b)

[0.61642183 0.47275275 0.00425973 0.30069276 0.65079668 0.49178119
 0.28926079 0.18455503 0.63834679 0.20505937 0.29462818 0.0364877 ]
[0.62970827 0.71405719 0.21673132 0.36498749 0.35797256 0.73741313
 0.25479341 0.49324205 0.34202123 0.63924406 0.74725149 0.15819108]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [136]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)
unique_names = np.unique(names)
print(unique_names)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [137]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print("a: {}".format(a))
print("b: {}".format(b))
a = np.setdiff1d(a, b)
print(a)

a: [1 2 3 4 5]
b: [5 6 7 8 9]
[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [138]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
print(sampleArray)
sampleArray = np.delete(sampleArray, 1, 0)
print(sampleArray)
sampleArray = np.insert(sampleArray, 1, newColumn, 0)
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 43 73]
 [53 94 66]]
[[34 43 73]
 [10 10 10]
 [53 94 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [139]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [140]:
array = np.random.rand(20)
array = array.reshape([4,5])
print(array)
res = np.cumsum(array)
res

[[0.53875384 0.71197253 0.70076611 0.77545146 0.8285677 ]
 [0.50893039 0.86970684 0.67530266 0.24406579 0.70080731]
 [0.46803431 0.90075809 0.28057242 0.5678957  0.45262346]
 [0.60509099 0.71473654 0.19787719 0.74138503 0.22626032]]


array([ 0.53875384,  1.25072637,  1.95149247,  2.72694393,  3.55551164,
        4.06444203,  4.93414887,  5.60945153,  5.85351732,  6.55432463,
        7.02235894,  7.92311702,  8.20368944,  8.77158515,  9.2242086 ,
        9.82929959, 10.54403613, 10.74191332, 11.48329835, 11.70955866])