# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [42]:
import numpy as np

2. Create a null vector of size 10 

In [43]:
np.array(10)

array(10)

3. Create a vector with values ranging from 10 to 49

In [44]:
vector = np.arange(start=10, stop=49)

4. Find the shape of previous array in question 3

In [45]:
vector.shape

(39,)

5. Print the type of the previous array in question 3

In [46]:
print(vector.dtype)

int64


6. Print the numpy version and the configuration


In [47]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
blas_info:
    libraries = ['cblas', 'blas', 'blas']
    library_dirs = ['/usr/lib64']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'blas']
    library_dirs = ['/usr/lib64']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
l

7. Print the dimension of the array in question 3


In [48]:
vector.ndim

1

8. Create a boolean array with all the True values

In [49]:
np.ones([1, 10], dtype=bool)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

9. Create a two dimensional array




In [50]:
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

10. Create a three dimensional array



In [51]:
np.zeros((2, 3,3))


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [52]:
np.flip(vector)

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [53]:
x = np.zeros(10)
print(x)
print("Update fifth value to 1")
x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [54]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [55]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = arr.astype(np.float)
print(arr.dtype)

int64
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [56]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
              
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

res = arr1 * arr2
print(res)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [57]:
arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])

res = arr1 == arr2

print(res)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [58]:
array = np.arange(start=0, stop=10)

array[array % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [59]:
np.where(array % 2 == 1, -1, array)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [60]:
arr = np.arange(10)

arr[4:8] = 12
print(arr)

[ 0  1  2  3 12 12 12 12  8  9]


20. Create a 2d array with 1 on the border and 0 inside

In [61]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [62]:
arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [63]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d[0][0][:] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [64]:
x = np.arange(10).reshape((5,2))
print("Before Slicing")
print(x)
print("After Slicing")
print(x[0, 0:])

Before Slicing
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
After Slicing
[0 1]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [65]:
x = np.arange(10).reshape((5,2))
print("Before Slicing")
print(x)
print("After Slicing")
print(x[0, 1:2])

Before Slicing
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
After Slicing
[1]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [66]:
x = np.arange(10).reshape((5,2))
print("Before Slicing")
print(x)
print("After Slicing")
print(x[0:3, :])

Before Slicing
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
After Slicing
[[0 1]
 [2 3]
 [4 5]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [67]:
x = np.random.rand(10, 10)
print("10 x 10 array: {}".format(x))
maximum_value = np.max(x)
minimum_value = np.min(x)
print("Maximum value: {}".format(maximum_value))
print("Minimum value: {}".format(minimum_value))

10 x 10 array: [[0.05967014 0.50224784 0.40442328 0.41229185 0.43005043 0.53575286
  0.39689906 0.20050912 0.56253333 0.1937826 ]
 [0.73921554 0.14409014 0.85414274 0.69133957 0.0067349  0.86927603
  0.26214077 0.54406055 0.20925095 0.70794163]
 [0.37370507 0.58612602 0.57273428 0.74342362 0.13558016 0.85009236
  0.16988037 0.95592317 0.87361096 0.70114025]
 [0.20574038 0.40787189 0.83075448 0.79605384 0.2155813  0.55747974
  0.34221683 0.82905314 0.82576815 0.66997623]
 [0.44845438 0.24295605 0.93126179 0.54532541 0.4445013  0.77395124
  0.19874623 0.04761896 0.92258913 0.10282147]
 [0.79816571 0.302275   0.33627074 0.48251629 0.06731037 0.01246182
  0.57415022 0.70884217 0.14641847 0.08479635]
 [0.11565287 0.32712935 0.24606998 0.45223503 0.37211987 0.30214376
  0.2750644  0.11599402 0.33184032 0.52422119]
 [0.25784269 0.12251557 0.70272879 0.05636991 0.57349558 0.62980708
  0.07328156 0.9233015  0.02056289 0.07582289]
 [0.53704215 0.62541362 0.12951244 0.00877852 0.23641304 0.585382

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [68]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [69]:
np.where(np.in1d(a, b))

(array([1, 3, 5, 7]),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [70]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
print("Names: {}".format(names))
data = np.random.randn(7, 4)
print("Data: {}".format(data))

names_sorted = np.where(names != "Will")[0]

for index in names_sorted:
    print("Name: {}, Data: {}".format(names[index], data[index]))

Names: ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
Data: [[ 0.59428447  0.10582964 -1.14892454  0.25820427]
 [-1.15663723 -0.20752839  0.69527169  0.17557452]
 [ 1.18617539 -0.06355948  0.00436757 -0.20275556]
 [ 0.13413245  0.43957921 -0.21502612 -0.39351922]
 [ 0.79486726  0.3945797   0.56718156 -0.82281968]
 [-0.39771117 -0.67709483  0.4204026  -1.23023988]
 [-0.92927382  0.03919076  1.76360735  0.46103907]]
Name: Bob, Data: [ 0.59428447  0.10582964 -1.14892454  0.25820427]
Name: Joe, Data: [-1.15663723 -0.20752839  0.69527169  0.17557452]
Name: Bob, Data: [ 0.13413245  0.43957921 -0.21502612 -0.39351922]
Name: Joe, Data: [-0.39771117 -0.67709483  0.4204026  -1.23023988]
Name: Joe, Data: [-0.92927382  0.03919076  1.76360735  0.46103907]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [71]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  
print("Names: {}".format(names))
data = np.random.randn(7, 4)
print("Data: {}".format(data))

names_sorted = np.where((names != "Will") & (names != "Joe"))[0]

for index in names_sorted:
    print("Name: {}, Data: {}".format(names[index], data[index]))

Names: ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
Data: [[ 1.03070759  0.7818496   0.52530897 -1.37444292]
 [-2.15900524  1.91789015 -0.27784741 -0.60389048]
 [-0.61883162  1.3185282  -0.1635721   0.34916722]
 [ 0.66720039 -0.92285795 -0.35834518 -1.76626196]
 [ 0.06753689 -0.44479536 -0.81639115  0.01740152]
 [-0.89098762  0.77196483  1.94331041 -0.40120342]
 [ 0.11404521 -1.7418469  -2.56166428  0.14153297]]
Name: Bob, Data: [ 1.03070759  0.7818496   0.52530897 -1.37444292]
Name: Bob, Data: [ 0.66720039 -0.92285795 -0.35834518 -1.76626196]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [72]:
array = np.arange(start=1, stop=16)
array = array.reshape([5, 3])
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [73]:
array = np.arange(start=1, stop=17)
array = array.reshape((2,2,4))

array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [74]:
array.T

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [75]:
x = np.arange(10)
print(x)

x = np.sqrt(x)
print(x)
x = np.where(x < 0.5, 0, x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [76]:
a = np.random.rand(12)
b = np.random.rand(12)
print(a)
print(b)

np.maximum(a, b)

[0.67248478 0.10130927 0.97968306 0.04901    0.39718749 0.83165767
 0.10434967 0.9997429  0.55216833 0.13454907 0.16910184 0.24683902]
[0.71416639 0.56131894 0.05278858 0.69975537 0.16916907 0.27405029
 0.14616909 0.14520174 0.76069706 0.99283837 0.54306843 0.28800731]


array([0.71416639, 0.56131894, 0.97968306, 0.69975537, 0.39718749,
       0.83165767, 0.14616909, 0.9997429 , 0.76069706, 0.99283837,
       0.54306843, 0.28800731])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [77]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)
unique_names = np.unique(names)
print(unique_names)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [78]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print("a: {}".format(a))
print("b: {}".format(b))
a = np.setdiff1d(a, b)
print(a)

a: [1 2 3 4 5]
b: [5 6 7 8 9]
[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [79]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
print(sampleArray)
sampleArray = np.delete(sampleArray, 1, 0)
print(sampleArray)
sampleArray = np.insert(sampleArray, 1, newColumn, 0)
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 43 73]
 [53 94 66]]
[[34 43 73]
 [10 10 10]
 [53 94 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [80]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [81]:
array = np.random.rand(20)
array = array.reshape([4,5])
print(array)
res = np.cumsum(array)
res

[[0.50445971 0.1248653  0.23358697 0.08645442 0.24222102]
 [0.49901343 0.80769378 0.90253582 0.98088252 0.18000206]
 [0.14202122 0.86018776 0.26126753 0.45442425 0.92272974]
 [0.06435802 0.48793944 0.65902837 0.7143706  0.71580296]]


array([0.50445971, 0.62932502, 0.86291199, 0.9493664 , 1.19158742,
       1.69060085, 2.49829462, 3.40083045, 4.38171296, 4.56171502,
       4.70373624, 5.563924  , 5.82519153, 6.27961578, 7.20234553,
       7.26670354, 7.75464298, 8.41367135, 9.12804194, 9.84384491])