# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np 

x = np.arange(10)
x
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
import numpy as np 
a = np.arange(10)
b = np.arange(10)

x = np.vstack((a, b))
x

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
import numpy as np 
a = np.arange(10)
b = np.arange(10)

x = np.hstack((a, b))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
x = np.random.rand(3,2)
print(x)
x = x.ravel()
print(x)

[[0.53178788 0.54077487]
 [0.22219729 0.70951687]
 [0.25600521 0.16881234]]
[0.53178788 0.54077487 0.22219729 0.70951687 0.25600521 0.16881234]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
x = np.random.rand(3,2, 5)
print(x)
x = x.ravel()
print(x)

[[[0.91180066 0.17336132 0.7053887  0.14291809 0.89502874]
  [0.67356539 0.04515372 0.37061524 0.97448952 0.80958384]]

 [[0.06919895 0.65772361 0.62329548 0.31804772 0.20016414]
  [0.86837953 0.72742864 0.76266863 0.87340652 0.82681752]]

 [[0.66245829 0.45305842 0.02399689 0.40523935 0.92494734]
  [0.77088326 0.86232661 0.29921389 0.33009258 0.85744284]]]
[0.91180066 0.17336132 0.7053887  0.14291809 0.89502874 0.67356539
 0.04515372 0.37061524 0.97448952 0.80958384 0.06919895 0.65772361
 0.62329548 0.31804772 0.20016414 0.86837953 0.72742864 0.76266863
 0.87340652 0.82681752 0.66245829 0.45305842 0.02399689 0.40523935
 0.92494734 0.77088326 0.86232661 0.29921389 0.33009258 0.85744284]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
x = np.arange(12)
print(x)
x = x.reshape(2,3,2)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
array = np.arange(25).reshape(5,5)
print(array)
np.square(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Question:8

### Create 5x6 an array and find the mean?

In [10]:
array = np.random.randint(30, size=(5,6))
print(array)
array.mean()

[[27 22  2 15  8 19]
 [10 27 24  7 19 28]
 [ 3 26  3 15 27 20]
 [15  0 20  5 23  0]
 [14  4  5 20  3 13]]


14.133333333333333

## Question:9

### Find the standard deviation of the previous array in Q8?

In [12]:
array.std()

15.0

## Question:10

### Find the median of the previous array in Q8?

In [16]:
np.median(array)

15.0

## Question:11

### Find the transpose of the previous array in Q8?

In [15]:
a = np.transpose(array)
a

array([[27, 10,  3, 15, 14],
       [22, 27, 26,  0,  4],
       [ 2, 24,  3, 20,  5],
       [15,  7, 15,  5, 20],
       [ 8, 19, 27, 23,  3],
       [19, 28, 20,  0, 13]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [18]:
array = np.arange(16).reshape(4,4)
print(array)
np.trace(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

## Question:13

### Find the determinant of the previous array in Q12?

In [20]:
np.linalg.det(array)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [21]:
array = np.arange(16)
print(array)
print(np.percentile(array, 5))
print(np.percentile(array, 95))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
0.75
14.25


## Question:15

### How to find if a given array has any null values?

In [25]:
data = [0,1,np.nan,3,np.nan,5,9]
array = np.array(data)
print(array)
print(np.isnan(array))

[ 0.  1. nan  3. nan  5.  9.]
[False False  True False  True False False]
