# Reading Recipes 

Note: Data file is recipes.csv Attached with jupyter notebook

In [42]:
#type your code here
import numpy as np

2. All of Alize’s recipes call for milk, eggs, sugar, flour, and butter. For example, her cupcake recipe calls for:

Flour Sugar Eggs Milk Butter 2 cups 0.75 cups 2 eggs 1 cups 0.5 cups Create a NumPy array that represents this data. Each element should be a number (i.e., 2 for “2 cups”). Save this array as cupcakes.

In [43]:
#type your code here
cupcakes = np.array([2,0.75,2,1,0.5])
cupcakes

array([2.  , 0.75, 2.  , 1.  , 0.5 ])

3. Alize’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv. Load this file into a variable called recipes.

###########Explore yourselves how to load a csv file in numpy#######

In [44]:
#type your code here
from numpy import genfromtxt
data = genfromtxt('recipes.csv', delimiter=',')
print(data)

[[2.    0.75  2.    1.    0.5  ]
 [1.    0.125 1.    1.    0.125]
 [2.75  1.5   1.    0.    1.   ]
 [4.    0.5   2.    2.    0.5  ]]


4.Display recipes using print.
Display recipes using print.


Each row represents a different recipe. Each column represents a different ingredient.

Recipe	       Cups of Flour	Cups of Sugar	Eggs	Cups of Milk	Cups of Butter

Cupcakes	         …	              …	          …	         …	              …

Pancake	             …                …	          …	         …	              …

Cookie	             …	              …	          …	         …	              …

Bread	             …	              …	          …	         …	              …

In [45]:
#type your code here
recipie = ["Cupcakes", "Pancake", "Cookie", "Bread"]

for i in range(4):
    print("{}: {} cups of flour, {} cups of sugar, {} eggs, {} cups of milk, {} cups of butter".format(recipie[i], data[i][0], data[i][1], data[i][2], data[i][3], data[i][4]))

Cupcakes: 2.0 cups of flour, 0.75 cups of sugar, 2.0 eggs, 1.0 cups of milk, 0.5 cups of butter
Pancake: 1.0 cups of flour, 0.125 cups of sugar, 1.0 eggs, 1.0 cups of milk, 0.125 cups of butter
Cookie: 2.75 cups of flour, 1.5 cups of sugar, 1.0 eggs, 0.0 cups of milk, 1.0 cups of butter
Bread: 4.0 cups of flour, 0.5 cups of sugar, 2.0 eggs, 2.0 cups of milk, 0.5 cups of butter


5.The 3rd column represents the number of eggs that each recipe needs.

Select all elements from the 3rd column and save them to the variable eggs.

In [46]:
#type your code here
eggs = data[:4, 2:-2]
print(eggs.reshape(1,4))

[[2. 1. 1. 2.]]


6.Which recipes require exactly 1 egg? Use a logical statement to get True or False for each value of eggs.

In [47]:
#type your code here
eggs_one = np.where(data[:4, 2:-2] == 1)
eggs_one

(array([1, 2]), array([0, 0]))

7.Alize is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).

You already have a variable for cupcakes. Create a variable for cookies with the data from the 3rd row.


In [48]:
#type your code here
cookies = data[2]
cookies

array([2.75, 1.5 , 1.  , 0.  , 1.  ])

8.
Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes. Save your new variable to double_batch.

In [49]:
#type your code here
double_batch = np.multiply(cupcakes, 2)
double_batch

array([4. , 1.5, 4. , 2. , 1. ])

9.
Create a new variable called grocery_list by adding cookies and double_batch.

In [51]:
#type your code here
grocery_list = np.vstack((cookies, double_batch))
grocery_list

array([[2.75, 1.5 , 1.  , 0.  , 1.  ],
       [4.  , 1.5 , 4.  , 2.  , 1.  ]])